sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: w1/UsCpUbjy/kL6I9fU7Q8ducvBhM10s0Jgkbgl+jKNI8DXBreXuXzKCJ9NRADecFcX96OPiFmHVcwouOGLSItxRyn87FeBSXFRHw3pBqd0XOq+DbhRI1IvM5XAvFJBfsey79QX+NjBYP6R7HOX2rap8fiH3+IBpIGsVu+pnwZIFkpjnFTHdbIPJH97bqKcl+qNqoYBLiLFxKS2OkaTRmy4TC1wCB80mq3DTEp8IUM0DFkYmVihjflanMzCTSwxMuLej/IzCR8lKkiEkS3TW1RNFG5Q4PXHamsvHv5tTfJNTawlH9WjosAAXcXZ2HwFpvxkHKNaQ6wZmD3j68BrPsdgrIc+sZxHDzlEhcNs9VI12T+hlkmi/cx8iW+iYBo6/E3NneYVE8oxGaPcbZspdNB0kYO6yP760no/3jlfew+EjkYCZ0KCDtlZ7n0LOZ0PNRKqHOUCj18jtfutYd7oCRYG/TXf8iSN0t5hVEfqRKUMSQUu02DHLkeYlIBanv3zjqwz9D5Hj1CY48kGnukXEjcG5p+jA2JF51dGsCHx+p1ETQOC2IGcI0HyBDsHRJPBlG0HPy1c5+30G1rUTscIDjBRHdsqgP5D/aY7aVc5H0mpXEosn5vKlkigvwZuB9yV6+e8J60/HU6ag6vJHfIJR9Ikc/S0S0fDhKt2ByJFseBk=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Ruth_4275
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy